spring:
  application:
    name: supplier-service

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8300/eureka/
  instance:
    hostname: localhost